In [88]:
import pandas as pd
import numpy as np

In [4]:
car = pd.read_csv("car data.csv")

In [3]:
car

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550,Mahindra,2006,425000,40,Diesel
2,2,Hyundai Grand i10,Hyundai,2014,325000,28000,Petrol
3,3,Ford EcoSport Titanium,Ford,2014,575000,36000,Diesel
4,4,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
811,811,Maruti Suzuki Ritz,Maruti,2011,270000,50000,Petrol
812,812,Tata Indica V2,Tata,2009,110000,30000,Diesel
813,813,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
814,814,Tata Zest XM,Tata,2018,260000,27000,Diesel
815,815,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [5]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  816 non-null    int64
 1   name        816 non-null    object
 2   company     816 non-null    object
 3   year        816 non-null    int64
 4   Price       816 non-null    int64
 5   kms_driven  816 non-null    int64
 6   fuel_type   816 non-null    object
dtypes: int64(4), object(3)
memory usage: 44.8+ KB

In [5]:
df.describe()

       Unnamed: 0         year         Price     kms_driven
count  816.000000   816.000000  8.160000e+02     816.000000
mean   407.500000  2012.444853  4.117176e+05   46275.531863
std    235.703203     4.002992  4.751844e+05   34297.428044
min      0.000000  1995.000000  3.000000e+04       0.000000
25%    203.750000  2010.000000  1.750000e+05   27000.000000
50%    407.500000  2013.000000  2.999990e+05   41000.000000
75%    611.250000  2015.000000  4.912500e+05   56818.500000
max    815.000000  2019.000000  8.500003e+06  400000.000000

In [6]:
car['year'].unique()

array([2007, 2006, 2014, 2012, 2013, 2016, 2015, 2010, 2017, 2008, 2018,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001],
      dtype=int64)

In [7]:
car['company'].unique()

array(['Hyundai', 'Mahindra', 'Ford', 'Maruti', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat', 'Force',
       'Mercedes', 'Land', 'Jaguar', 'Jeep', 'Volvo'], dtype=object)

In [8]:
car['name'].unique()

array(['Hyundai Santro Xing', 'Mahindra Jeep CL550', 'Hyundai Grand i10',
       'Ford EcoSport Titanium', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente', 'Maruti Suzuki Alto',
       'Skoda Fabia Classic', 'Maruti Suzuki Stingray',
       'Hyundai Elite i20', 'Mahindra Scorpio SLE', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Hyundai i20 Sportz',
       'Maruti Suzuki Vitara', 'Mahindra Bolero DI',
       'Maruti Suzuki Swift', 'Maruti Suzuki Wagon', 'Toyota Innova 2.0',
       'Renault Lodgy 85', 'Skoda Yeti Ambition', 'Maruti Suzuki Baleno',
       'Renault Duster 110', 'Renault Duster 85', 'Honda City 1.5',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5',
       'Honda City', 'Datsun Redi GO', 'Maruti Suzuki SX4',
       'Mitsubishi Pajero Sport', 'Honda City ZX', 'Tata Indigo eCS',
       'Volkswagen Polo Highline', 'Chevrolet Spark LS',
       'Renault Duster 110PS', 'Mini Cooper S', 'Skoda Fabia 1.2L',
       'Renault Duster', 'Mahindra Scorpio S4', 'Mahindra Scorpio VLX',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Volkswagen Vento Highline', 'Hyundai i20 Magna',
       'Toyota Corolla Altis', 'Hyundai Verna Transform', 'BMW 3 Series',
       'Maruti Suzuki A', 'Toyota Etios GD', 'Ford Figo Diesel',
       'Chevrolet Beat LT', 'BMW 7 Series', 'Mahindra XUV500 W8',
       'Hyundai i10 Magna', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Ertiga', 'Honda Amaze 1.2', 'Hyundai i20 Asta',
       'Maruti Suzuki Eeco', 'Maruti Suzuki Esteem', 'Maruti Suzuki Ritz',
       'Toyota Etios Liva', 'Chevrolet Spark', 'Nissan Micra XV',
       'Chevrolet Beat', 'Ford EcoSport Trend', 'Tata Indica V2',
       'Hindustan Motors Ambassador', 'Toyota Innova 2.5',
       'Volkswagen Jetta Highline', 'Volkswagen Polo Comfortline',
       'Volkswagen Polo', 'Mahindra Scorpio', 'Nissan Sunny',
       'Renault Kwid', 'Chevrolet Spark LT', 'Fiat Punto Emotion',
       'Hyundai i10 Sportz', 'Chevrolet Beat LS', 'Tata Indigo CS',
       'Hyundai Eon Era', 'Mahindra XUV500', 'Ford Fiesta', 'Hyundai i20',
       'Hyundai Fluidic Verna', 'Fiat Petra ELX', 'Maruti Suzuki Ciaz',
       'Maruti Suzuki Zen', 'Hyundai Creta 1.6', 'Mahindra Scorpio SLX',
       'Tata Nano Cx', 'Tata Sumo Victa', 'Volkswagen Passat Diesel',
       'Renault Scala RxL', 'Hyundai i20 Active', 'Mahindra Xylo E4',
       'Mahindra Jeep MM', 'Mahindra Bolero SLE', 'Force Motors Force',
       'Toyota Etios', 'Honda City VX', 'Mahindra Thar CRDe',
       'Audi A4 1.8', 'Mercedes Benz GLA', 'Land Rover Freelander',
       'Renault Kwid RXT', 'Tata Aria Pleasure', 'Mercedes Benz B',
       'Datsun GO T', 'Honda Jazz VX', 'Chevrolet Tavera Neo',
       'Hyundai Eon Sportz', 'Tata Sumo Gold', 'Chevrolet Enjoy 1.4',
       'Nissan Terrano XL', 'Maruti Suzuki Maruti', 'Renault Kwid 1.0',
       'Hyundai Accent GLX', 'Mahindra TUV300 T4', 'Honda Accord',
       'Mahindra Scorpio 2.6', 'Honda Mobilio', 'Skoda Laura',
       'Tata Manza Aura', 'Chevrolet Sail UVA', 'Audi A4 2.0',
       'Hyundai Elantra SX', 'Mahindra KUV100 K8', 'Hyundai i10',
       'Hyundai Accent', 'Hyundai Verna', 'Toyota Fortuner',
       'Mahindra Bolero Power', 'Skoda Rapid Elegance',
       'Tata Vista Quadrajet', 'Chevrolet Beat Diesel',
       'Hyundai Verna 1.4', 'Maruti Suzuki Versa', 'Tata Indigo LX',
       'Volkswagen Vento Konekt', 'Mercedes Benz C', 'Maruti Suzuki Omni',
       'Hyundai Sonata Transform', 'Honda Jazz S', 'Mahindra Scorpio W',
       'Honda Brio V', 'Mahindra TUV300 T8', 'Nissan X Trail',
       'Ford Ikon 1.3', 'Toyota Fortuner 3.0', 'Tata Manza ELAN',
       'Mercedes Benz A', 'Tata Indigo LS', 'Hyundai Verna 1.6',
       'BMW 5 Series', 'Skoda Superb 1.8', 'Audi Q3 2.0',
       'Ford Figo Duratorq', 'Mahindra Logan Diesel', 'Tata Nano GenX',
       'Honda City SV', 'Ford Figo Petrol', 'Toyota Corolla H2',
       'Hyundai Xcent Base', 'Hyundai Accent Executive', 'Tata Zest XE',
       'Mahindra XUV500 W6', 'Tata Tigor Revotron', 'Maruti Suzuki 800',
       'Honda Mobilio S', 'Tata Indica', 'Honda Brio VX', 'Tata Nano Lx',
       'Jaguar XE XE', 'Hyundai Eon Magna', 'Hyundai Eon D',
       'Maruti Suzuki Estilo', 'Mahindra Scorpio Vlx',
       'Mitsubishi Lancer 1.8', 'Ford Fiesta SXi', 'Audi A6 2.0',
       'Hyundai Getz Prime', 'Hyundai Santro', 'Chevrolet Beat PS',
       'BMW X1 xDrive20d', 'Tata Nano', 'Chevrolet Cruze LTZ',
       'Mahindra XUV500 W10', 'Hyundai Accent GLE', 'Force Motors One',
       'Chevrolet Spark 1.0', 'Renault Duster 85PS', 'Chevrolet Enjoy',
       'Jeep Wrangler Unlimited', 'Hyundai Verna VGT',
       'Maruti Suzuki Celerio', 'Tata Zest Quadrajet', 'Hyundai i10 Era',
       'Tata Indigo Marina', 'Hyundai Xcent SX', 'Tata Nano LX',
       'Mahindra Xylo E8', 'Tata Manza Aqua', 'Tata Venture EX',
       'Skoda Octavia Classic', 'Ford Ikon 1.6', 'Nissan Sunny XL',
       'Volkswagen Polo Trendline', 'Hyundai Elantra 1.8',
       'Tata Indica eV2', 'Jaguar XF 2.2', 'Audi Q5 2.0',
       'BMW X1 sDrive20d', 'Maruti Suzuki S',
       'Volkswagen Vento Comfortline', 'Mahindra KUV100',
       'Volkswagen Jetta Comfortline', 'Volvo S80 Summum', 'BMW X1',
       'Renault Duster RxL', 'Honda WR V', 'Mahindra Scorpio LX',
       'Audi A3 Cabriolet', 'Hyundai Santro AE', 'Mahindra Xylo D2',
       'Hyundai Getz GLE', 'Nissan Micra XL', 'Chevrolet Tavera LS',
       'Tata Tiago Revotron', 'Tata Tiago Revotorq', 'Ford Fusion 1.4',
       'Fiat Linea Emotion', 'Toyota Corolla', 'Tata Sumo Grande',
       'Volkswagen Polo Highline1.2L', 'Hyundai Creta', 'Tata Bolt XM',
       'Datsun Go Plus', 'Ford Endeavor 4x4', 'Mahindra Logan',
       'Chevrolet Sail 1.2', 'Tata Manza', 'Toyota Etios G',
       'Toyota Qualis', 'Mahindra Quanto C4', 'Hyundai i20 Select',
       'Hyundai Getz', 'Skoda Fabia', 'Tata Zest XM'], dtype=object)

In [11]:
car['Price'].unique()

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  290000,   95000,
        180000,  385000,  105000,  650000,  689999,  448000,  549000,
        501000,  489999,  280000,  349999,  284999,  345000,  499999,
        235000,  249999, 1475000,  395000,  220000,  170000,   85000,
        200000,  570000,  110000,  448999, 1891111,  159500,  344999,
        449999,  865000,  699000,  375000,  224999, 1200000,  195000,
        351000,  240000,   90000,  155000,  600000,  189500,  210000,
        390000,  135000, 1600000,  701000,  265000,  525000,  372000,
        635000,  550000,  485000,  329500,  251111,  569999,   69999,
        299999,  399999,  450000,  270000,  158400,  179000,  125000,
        299000,  150000,  285000,  340000,   70000,  289999,  849999,
        749999,  274999,  984999,  599999,  244999,  474999,  245000,
        169500,  275000,  370000,  168000,  145000,   98500,  209000,
        185000,  900000,  699999,  199999,  544999,  199000,  540000,
         49000,  700000,   55000,  895000,  355000,  565000,  365000,
         40000,  400000,  330000,  580000,  379000,  219000,  519000,
        730000, 2000000, 2100000, 1400000,  311000,  855000,  535000,
        178000,  300000,  255000,  549999,  380000,   57000,  410000,
        225000,  120000,   59000,  599000,  675000,   72500,  610000,
        230000,  520000,  524999,  424999,  644999,  584999,  799999,
        444999,  649999,  944999,  574999,  374999,  130000,  401000,
       1350000,  174999,  239999,   99999,  324999, 1074999, 1130000,
        149000,  770000,   30000,  335000,  399000,   65000,  169999,
        165000,  560000,  950000,  715000,   45000,  940000,  155555,
       1500000,  495000,  800000, 1299000,  530000, 1499000,   32000,
        405000,  760000,  750000,  419000,  140000, 1540000,  123000,
        498000,  480000,  488000, 1525000,  548900,  725000,   99000,
         52000, 2800000,  499000,  381000,  278000,  690000,  260000,
         90001,  115000, 1599000,  159000,   51999,  215000,   35000,
       1150000,  269000,   60000,  430000, 8500003,  401919,  490000,
        424000,  205000,  549900,  435000,  189700,  389700,  360000,
        295000,  114990, 1065000,  470000,   48000,  188000,  465000,
        179999, 2190000, 2390000, 1075000,  475000, 1025000,  615000,
       1900000, 1490000, 1510000, 1850000,  790000, 1725000, 1225000,
         68000,  970000, 3100000,  899000,   88000,   53000,  568500,
         71000,  590000,  795000,   42000,  189000,  162000,   35999,
       2900000,   39999,   50500,  510000,  860000,  500001], dtype=int64)

In [12]:
car['kms_driven'].unique()

array([ 45000,     40,  28000,  36000,  41000,  25000,  24530,  60000,
        30000,  32000,  48660,   4000,  16934,  43000,  35550,  39522,
        39000,  55000,  72000,  15975,  70000,  23452,  35522,  48508,
        15487,  82000,  20000,  68000,  38000,  27000,  33000,  46000,
        16000,  47000,  35000,  30874,  15000,  29685, 130000,  19000,
        54000,  13000,  38200,  22000,  50000,  13500,   3600,  45863,
        60500,  12500,  18000,  13349,  29000,  44000,  42000,  14000,
        49000,  36200,  51000, 104000,  33333,  33600,   5600,   7500,
        24330,  65480, 200000,  59000,  99000,   2800,  21000,  11000,
        66000,   3000,   7000,  38500,  37200,  43200,  24800,  45872,
        40000,  11400,  97200,  52000,  31000, 175430,  37000,  65000,
         3350,  75000,  62000,  73000,   2200,  54870,  34580,  97000,
           60,  80200,   3200,      0,   5000,    588,  71200, 175400,
         9300,  56758,  10000,  56450,  56000,  32700,   9000,     73,
       160000,  58559,  57000, 170000,  80000,   6821,  23000,  34000,
         1800, 400000,  48000,  90000,  12000,  69900, 166000,    122,
        36469,   7800,  24695,  15141,  59910, 100000,   4500, 129000,
          300, 131000, 111111,  59466,  25500,  44005,   2110,  43222,
       100200,     65, 140000, 103553,  58000, 120000,  49800,    100,
        81876,   6020,  55700,  18500,  53000,  35500,  22134,   1000,
         8500,  87000,   6000,   8000,  55800,  56400,  72160,  11500,
       133000,   2000,  88000,  65422, 117000, 150000,  10750,   6800,
         9800,  57923,  30201,   6200,  37518,  24652,    383,  95000,
         3528,  52500,  47900,  52800, 195000,  48008,  48247,   9400,
        64000,   2137,  10544, 147000,  90001,  48006,  74000,  85000,
        29500,  39700,  67000,  19336,  60105,  45933, 102563,  28600,
        41800, 116000,  42590,   7400,  54500,  76000,  11523,  38600,
        95500,  37458,  85960,  12516,  30600,   2550,  62500,  69000,
        28400,  68485,   3500,  85455,  63000,   1600,  77000,  26500,
         2875,  13900,   1500,   2450,   1625,  33400,  60123, 137495,
        91200, 146000, 100800,   2100,   2500, 132000], dtype=int64)

In [13]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [14]:
car

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550,Mahindra,2006,425000,40,Diesel
2,2,Hyundai Grand i10,Hyundai,2014,325000,28000,Petrol
3,3,Ford EcoSport Titanium,Ford,2014,575000,36000,Diesel
4,4,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
811,811,Maruti Suzuki Ritz,Maruti,2011,270000,50000,Petrol
812,812,Tata Indica V2,Tata,2009,110000,30000,Diesel
813,813,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
814,814,Tata Zest XM,Tata,2018,260000,27000,Diesel
815,815,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

## Checking Proper Data

In [16]:
car['name'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: name
Non-Null Count  Dtype
--------------  -----
816 non-null    object
dtypes: object(1)
memory usage: 6.5+ KB

In [17]:
car['company'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: company
Non-Null Count  Dtype
--------------  -----
816 non-null    object
dtypes: object(1)
memory usage: 6.5+ KB

In [18]:
car['year'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: year
Non-Null Count  Dtype
--------------  -----
816 non-null    int64
dtypes: int64(1)
memory usage: 6.5 KB

In [19]:
car['Price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: Price
Non-Null Count  Dtype
--------------  -----
816 non-null    int64
dtypes: int64(1)
memory usage: 6.5 KB

In [20]:
car['kms_driven'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: kms_driven
Non-Null Count  Dtype
--------------  -----
816 non-null    int64
dtypes: int64(1)
memory usage: 6.5 KB

In [21]:
car['fuel_type'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: fuel_type
Non-Null Count  Dtype
--------------  -----
816 non-null    object
dtypes: object(1)
memory usage: 6.5+ KB

In [22]:
car['name'].describe()

count                     816
unique                    254
top       Maruti Suzuki Swift
freq                       51
Name: name, dtype: object

In [23]:
car.shape

(816, 7)

In [25]:
car['name']

0         Hyundai Santro Xing
1         Mahindra Jeep CL550
2           Hyundai Grand i10
3      Ford EcoSport Titanium
4                   Ford Figo
                ...
811        Maruti Suzuki Ritz
812            Tata Indica V2
813      Toyota Corolla Altis
814              Tata Zest XM
815        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [26]:
car['company']

0       Hyundai
1      Mahindra
2       Hyundai
3          Ford
4          Ford
         ...
811      Maruti
812        Tata
813      Toyota
814        Tata
815    Mahindra
Name: company, Length: 816, dtype: object

In [27]:
car['Price']

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
811    270000
812    110000
813    300000
814    260000
815    390000
Name: Price, Length: 816, dtype: int64

In [28]:
car['year']

0      2007
1      2006
2      2014
3      2014
4      2012
       ...
811    2011
812    2009
813    2009
814    2018
815    2013
Name: year, Length: 816, dtype: int64

In [29]:
car['kms_driven']

0       45000
1          40
2       28000
3       36000
4       41000
        ...
811     50000
812     30000
813    132000
814     27000
815     40000
Name: kms_driven, Length: 816, dtype: int64

In [30]:
car['fuel_type']

0      Petrol
1      Diesel
2      Petrol
3      Diesel
4      Diesel
        ...
811    Petrol
812    Diesel
813    Petrol
814    Diesel
815    Diesel
Name: fuel_type, Length: 816, dtype: object

In [31]:
car.describe()

       Unnamed: 0         year         Price     kms_driven
count  816.000000   816.000000  8.160000e+02     816.000000
mean   407.500000  2012.444853  4.117176e+05   46275.531863
std    235.703203     4.002992  4.751844e+05   34297.428044
min      0.000000  1995.000000  3.000000e+04       0.000000
25%    203.750000  2010.000000  1.750000e+05   27000.000000
50%    407.500000  2013.000000  2.999990e+05   41000.000000
75%    611.250000  2015.000000  4.912500e+05   56818.500000
max    815.000000  2019.000000  8.500003e+06  400000.000000

## Cars Greater Than 60 Lakh

In [39]:
car[car['Price']<6e6]

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550,Mahindra,2006,425000,40,Diesel
2,2,Hyundai Grand i10,Hyundai,2014,325000,28000,Petrol
3,3,Ford EcoSport Titanium,Ford,2014,575000,36000,Diesel
4,4,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
810,811,Maruti Suzuki Ritz,Maruti,2011,270000,50000,Petrol
811,812,Tata Indica V2,Tata,2009,110000,30000,Diesel
812,813,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
813,814,Tata Zest XM,Tata,2018,260000,27000,Diesel
814,815,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

## Model

In [40]:
# dropping price because it's not a feature
x = car.drop(columns='Price')
y = car['Price']

In [41]:
x

     Unnamed: 0                    name   company  year  kms_driven fuel_type
0             0     Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1             1     Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2             2       Hyundai Grand i10   Hyundai  2014       28000    Petrol
3             3  Ford EcoSport Titanium      Ford  2014       36000    Diesel
4             4               Ford Figo      Ford  2012       41000    Diesel
..          ...                     ...       ...   ...         ...       ...
810         811      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811         812          Tata Indica V2      Tata  2009       30000    Diesel
812         813    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813         814            Tata Zest XM      Tata  2018       27000    Diesel
814         815      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 6 columns]

In [42]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int64

In [70]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y , test_size=0.2)

In [71]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [72]:
ohe = OneHotEncoder()
ohe.fit(x[['name', 'company','fuel_type']])

OneHotEncoder()

In [73]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                        remainder='passthrough')

In [74]:
lr = LinearRegression()

In [75]:
pipe = make_pipeline(column_trans,lr)

In [76]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [77]:
y_pred = pipe.predict(x_test)

In [78]:
y_pred

array([ 442321.1204134 ,  634379.27158595,  409898.40137657,
         85969.11987306,  573499.47090563,  681410.57742976,
        458859.94124135,  449935.02281059,  145654.94867773,
        280096.27688807,  252156.56608217,  200738.99572466,
        347070.14874771,  352263.64531571,  523141.56598856,
        641887.56380425,  593364.27669647,  392556.31043682,
        146215.22641772,  302646.07397567,  388161.31645088,
        350640.45232658,  399345.30812275,  107833.59518565,
         -7910.53918304,  333819.58322052,  -77092.57953431,
        412258.39036648,  420695.98563205,  341903.64682778,
        298540.37511737,  323202.35477074,  319388.87618233,
        180485.98145115,  602995.08264313,  122593.49093819,
       1299091.37692198,  402844.01833297,  309224.73760118,
        248365.36495463,  375503.96265711,  342263.53465144,
        244101.24792005,  257407.57796888,  406759.76994926,
        422774.17158495,  123704.75459538,  187856.30548723,
        472831.23356965,  539953.78419548,  112865.3891839 ,
       1311471.63436791,  316388.62675886,  385297.35572586,
        176333.41305992,  620255.67899943,  372572.8284901 ,
        393451.90789163,  468208.03687716,  263472.85987404,
        972080.15865817, 1026810.69822511,  285180.17985006,
        963047.35381281,  250466.07186992,  223610.90416707,
        417431.40262629,  -18201.11038072,  328835.77604508,
        -12301.8901673 ,  738343.21184126,  372316.3180441 ,
        688642.49760558,  677141.60837484,  570586.29038253,
        476227.75638726,  320372.36504834,  522060.70534983,
        264231.91129104,  440605.11236196,  171788.33657583,
         51751.61466765,  132720.92887795, -117313.70404192,
         46742.62103492,  259495.40288386,  287464.57570503,
        458404.58610144,  522509.3147723 ,  251696.86735931,
        492398.16210902,  561085.14816105,  621336.53963815,
         89071.51257645,  290275.88797634,  150116.17451666,
        538385.59227904,  431901.74964289,  635348.21663252,
        154510.59942044,  452860.02489375,  178040.01713662,
        462991.20289081,  210880.70023938,  193857.14851861,
        239681.25878242,  695074.27174808,  289631.37542782,
        352933.67192585,  397858.9976318 ,   94939.32488907,
        189192.37336748,  245286.12160822,  466527.76519331,
        326410.54514306,  -15441.04676837,  233591.50093509,
        662479.75482469,   -7499.32547083,  461108.00730491,
        187893.72652867,  274233.09024899,  485369.77116624,
        703060.3194808 ,  409352.80318042,  420979.97210659,
        421479.90331978,  115957.78312302,  439248.80359181,
        245543.16789432,  415530.80049084,  454524.28592855,
          7982.57427383,  438656.13691511,  249128.74984011,
        235480.97651244,  703438.59573938,  538189.0721629 ,
        372914.85066116,  261024.44434393,  331700.76878559,
        192434.95528366,  690643.90504539,  495530.48967202,
        132833.00060456,   45000.00330868,  725988.53406727,
        369374.71707992,  504163.24070594,  187795.46647061,
        432748.73065546,  463206.75894763,  147954.08394643,
        494404.90491357,  133456.89122239, -177442.07731298,
       1309773.58595384,  362015.19465961,  281713.49322234,
        509755.27051121,  313837.60221747,  601306.24554709,
        418019.42512123])

In [79]:
r2_score(y_test,y_pred)

0.47910285979338374

In [87]:
scores = []
for i in range(1000):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred = pipe.predict(x_test)
    print(r2_score(y_test,y_pred),i)
    scores.append(r2_score(y_test,y_pred))

0.6661069038751815 0
0.5048147429003093 1
0.6289449351607963 2
0.5556453423067457 3
0.8048033304001345 4
0.6629841880665786 5
0.6402903078808225 6
0.633290220253633 7
0.6842085346809162 8
0.5969262408589701 9
0.64623593832131 10
0.612071339521751 11
0.47588230839095247 12
0.6674934171683764 13
0.5726751364143832 14
0.6937720432057455 15
0.5004376339306607 16
0.6728040436436586 17
0.6189082659360687 18
0.6414695521842083 19
0.6511108764381215 20
0.6315827262871003 21
0.7110724747181748 22
0.651644682036574 23
0.5588678349522056 24
0.5019229054321841 25
0.6760818178707666 26
0.6972069121039444 27
0.734095079784996 28
0.6173233452061315 29
0.6161753411162991 30
0.6707447575207501 31
0.7578370758624349 32
0.7892895059416031 33
0.5769382612517833 34
0.6677681058307268 35
0.5907954228474013 36
0.6216484582533085 37
0.5593891737179069 38
0.7232143551089669 39
0.37139069039380745 40
0.6844222032729104 41
0.5788543214321622 42
0.6639119881414155 43
0.6685949529103836 44
0.6954475680261978 45
0.510475779711472 46
0.6007437489033096 47
0.7663307022686899 48
0.6876123920141501 49
0.5180124996372536 50
0.6049865413940614 51
0.6378672631284845 52
0.67337126823685 53
0.5514623067395412 54
0.6909305979859636 55
0.7182188571240062 56
0.7276752293703921 57
0.7812710328231798 58
0.5102207397876541 59
0.5833482452776368 60
0.5336999323459671 61
0.4459999968786127 62
0.6267316400736855 63
0.6139237635347058 64
0.6396278942526796 65
0.4873163878961091 66
0.6598340612649155 67
0.6353542723772695 68
0.7322685635167369 69
0.6912327319530986 70
0.7199598199323507 71
0.5891918659827222 72
0.6876503579096125 73
0.5646958378589702 74
0.5754320377454488 75
0.4602037444422362 76
0.6091172570417486 77
0.5758273977467046 78
0.6484588177348335 79
0.6079875497255369 80
0.6147703412276014 81
0.6866406506570752 82
0.7467200064750152 83
0.6545956328081194 84
0.6406282815070086 85
0.6718173605795016 86
0.5578199584096166 87
0.617058286343241 88
0.6485022851561456 89
0.6843495790289409 90
0.5655199098354237 91
0.6895892166046247 92
0.5117177667894002 93
0.6426835644545407 94
0.6673474817038253 95
0.6532095829317559 96
0.6807584560148234 97
0.6829806142163777 98
0.5962538739696508 99
0.6967277686351269 100
0.6639015104605805 101
0.6972716737052704 102
0.6055058371473337 103
0.7128964768685624 104
0.5660784184356509 105
0.611303713775203 106
0.5887921768428688 107
0.561316491880625 108
0.707181573384611 109
0.6799969631902552 110
0.6580688614451274 111
0.46693078790447284 112
0.6901152018591366 113
0.6943970241787358 114
0.5940270650831674 115
0.6004436226593522 116
0.6624271256925227 117
0.46852254862202003 118
0.7271851343525781 119
0.6721029676468464 120
0.6044410494525747 121
0.7178935686843455 122
0.6387959775515294 123
0.8221430784454546 124
0.7382793573704729 125
0.6450226973069788 126
0.6180723191010096 127
0.5584166230816606 128
0.5518336442710987 129
0.6227243858133062 130
0.54627356109586 131
0.6901490257525928 132
0.5872841697911102 133
0.7154191818356241 134
0.7783908361591687 135
0.5491471202745035 136
0.7176153654392105 137
0.6547431024543839 138
0.5597699144084327 139
0.722836815680701 140
0.5962187461328196 141
0.6650807496721804 142
0.7224398230633449 143
0.6403284685500416 144
0.5619085805735409 145
0.6593619023696975 146
0.5770511725482861 147
0.566471442002008 148
0.6559364720201286 149
0.6250722983182087 150
0.7768034721840602 151
0.5596524452373081 152
0.5105034239737763 153
0.6121280465730486 154
0.661697780582955 155
0.38880803894114013 156
0.7288486727055238 157
0.6281310960778801 158
0.6826523353402206 159
0.629183176498348 160
0.5993963607508519 161
0.6709526897151962 162
0.5642289597197834 163
0.5611545481367977 164
0.6857649476965811 165
0.6618319232568661 166
0.5174716880334242 167
0.5725767312187253 168
0.6951777454424433 169
0.6839310138523873 170
0.6602793797623645 171
0.8135614828412784 172
0.7124501094972628 173
0.5678348617262298 174
0.6242283048901887 175
0.6919428968104426 176
0.6191075370501131 177
0.711163858000036 178
0.6842330596603643 179
0.6291304688521654 180
0.6205846739114196 181
0.6873967254049016 182
0.6512159727518136 183
0.48839977189070716 184
0.6584900635306506 185
0.7420281685140769 186
0.6727575795983365 187
0.6893915966693431 188
0.5777520965031503 189
0.7071999626396412 190
0.6497406289816622 191
0.5890369152265083 192
0.6864185528858335 193
0.7253858425807562 194
0.631723578375638 195
0.6420881445094911 196
0.7498962150242483 197
0.4005872845109969 198
0.7196831991459094 199
0.6947964608165134 200
0.47195714250124443 201
0.598419100474146 202
0.7744606236209868 203
0.5845653691421574 204
0.6539407466353278 205
0.7796388505699898 206
0.5883713784503627 207
0.7258129018788273 208
0.3144092097444938 209
0.5100163186399883 210
0.5249243337522191 211
0.5971251633916974 212
0.6302347256320984 213
0.683636575041314 214
0.6110852893122176 215
0.5396708697179441 216
0.5996125910284911 217
0.5527629715275797 218
0.5894948968982014 219
0.5904278168627687 220
0.6956882947271172 221
0.49370887357433035 222
0.5084948494188096 223
0.5562483388034287 224
0.7302549591176946 225
0.7541058503315603 226
0.6411758954672844 227
0.7434933444966907 228
0.594115201799486 229
0.5722876253020617 230
0.6048344362959974 231
0.6427523574561571 232
0.4447397595051926 233
0.7369358821242951 234
0.5981081825789019 235
0.6963562206660369 236
0.6207097844632288 237
0.5250277803119098 238
0.6038647920329738 239
0.5802779266367111 240
0.4961265114726404 241
0.5418078215220925 242
0.6508257025848393 243
0.5015113262995217 244
0.7133355546112357 245
0.7859013695031519 246
0.725319824846167 247
0.7888208730824045 248
0.5488653118650362 249
0.6197780172459508 250
0.5291997617301876 251
0.5698173084558441 252
0.6468971641506591 253
0.5914229730766905 254
0.7756310096707778 255
0.5684325337879417 256
0.700643193283828 257
0.6640216240417398 258
0.5788366979333182 259
0.7168928772287331 260
0.7419373683847001 261
0.7050207614175965 262
0.7173109511765765 263
0.6440880732849329 264
0.5867665439999888 265
0.6535062824246675 266
0.6607581548642963 267
0.49480659527863136 268
0.564188421911527 269
0.6404319386466809 270
0.5605569774057557 271
0.6228848497998216 272
0.6039880627705967 273
0.7176229956972368 274
0.643369694875416 275
0.7558788310296026 276
0.6957390718827305 277
0.6283201320369752 278
0.7923988124129049 279
0.6646928151218793 280
0.6469811863436734 281
0.698612730140511 282
0.7427708644437285 283
0.720058910871825 284
0.5751222446819091 285
0.7293411649728482 286
0.6068925578624744 287
0.35100315472683474 288
0.46980763749905396 289
0.5346179419203261 290
0.6880956199907009 291
0.5547450885194456 292
0.747334116542888 293
0.7981195612334497 294
0.6336970425759971 295
0.7276112303495839 296
0.7061794460010109 297
0.5549850785476959 298
0.6831997758088533 299
0.7800952251513162 300
0.7269413332904192 301
0.7642685888920854 302
0.47220482057545854 303
0.6213343401395772 304
0.6031607927088374 305
0.7835731763409763 306
0.6984466780059695 307
0.6525234435435772 308
0.7214898170141076 309
0.6805116993055327 310
0.6158937629731628 311
0.5246620209647571 312
0.5129915657665457 313
0.5553442047902132 314
0.7424188208785962 315
0.5954966758019395 316
0.6047162328272575 317
0.6348288781520872 318
0.5286520324173908 319
0.4846459006842695 320
0.6018049456784612 321
0.5440479691070557 322
0.5796921641004102 323
0.6276630778331964 324
0.5459688863421697 325
0.5959221867497725 326
0.7245155674757622 327
0.6997296733215332 328
0.5276684819120296 329
0.650469112960119 330
0.5114096520293347 331
0.6088773914027621 332
0.5835266249074715 333
0.7023885280443496 334
0.6193436949199029 335
0.5097483606056681 336
0.6796742538831193 337
0.6246082618060218 338
0.5720234233974412 339
0.6888940783263539 340
0.7317450274196758 341
0.6065063147640684 342
0.6711673261845321 343
0.6999651566315426 344
0.6436359009084685 345
0.6613991095201875 346
0.5919185265931671 347
0.7152733389402346 348
0.6299027247583248 349
0.7369650219853658 350
0.7131609191745547 351
0.5895828954503446 352
0.47675062254145884 353
0.7265996513766323 354
0.674602530087622 355
0.7045356629874222 356
0.6624525312170327 357
0.7045653344186913 358
0.6010098599473604 359
0.7153093138200564 360
0.6725911855212711 361
0.5596344841872498 362
0.7001008386625778 363
0.7178662910561106 364
0.5696296503208461 365
0.6956717342814946 366
0.4087556123687688 367
0.7167035694176082 368
0.7386247691298857 369
0.6948641399742876 370
0.6377121266024353 371
0.6541666748052268 372
0.6618769325268496 373
0.5317810738467745 374
0.5783420794738582 375
0.6883804535307472 376
0.5709225048868114 377
0.7181353103497681 378
0.769965602204532 379
0.6312414354928532 380
0.6950110806388454 381
0.7073085712385954 382
0.8032559628304319 383
0.6930144400913729 384
0.7120835393789755 385
0.6786319984589535 386
0.608335311770491 387
0.5743143336780656 388
0.41617692287981 389
0.7296670967556524 390
0.580443276407025 391
0.8063417436485907 392
0.40143287225058844 393
0.6471186390622179 394
0.6794809795934154 395
0.564541720716358 396
0.6058122967147821 397
0.6929313182536265 398
0.6711036558596584 399
0.6262193029662348 400
0.5875838791321878 401
0.5741425731353278 402
0.5062500230654472 403
0.574568132170272 404
0.5864727466985733 405
0.5834686419823361 406
0.6261334476204039 407
0.6509358132020577 408
0.6617006927122324 409
0.6832383232208388 410
0.6634152033722784 411
0.6620959828648902 412
0.5275630351805681 413
0.5985551189071123 414
0.5482973611500017 415
0.4873917077540266 416
0.7050520145513037 417
0.6854946108554597 418
0.6933669556043598 419
0.7059892582848584 420
0.663211649032434 421
0.6835668356765865 422
0.6489961386686207 423
0.6259643452372268 424
0.5752693618035813 425
0.4470518088016685 426
0.6938071155441157 427
0.5124076699983333 428
0.6615622926199727 429
0.6900457504741533 430
0.7875609700805803 431
0.6465668049550308 432
0.8455753664645759 433
0.6170937257561162 434
0.769998210204318 435
0.596637743868915 436
0.7062554069492317 437
0.622045615049939 438
0.7101010965827887 439
0.6514761101026911 440
0.6769447985844654 441
0.6008756112866241 442
0.8082193719103394 443
0.7686122490470026 444
0.7499698234481758 445
0.7219942205773475 446
0.6217716142401002 447
0.5568369159402449 448
0.7411365093441444 449
0.7668242943948425 450
0.5480569646958316 451
0.583706328294182 452
0.6375596864607656 453
0.655634539843632 454
0.6504681958215366 455
0.511685064626204 456
0.530719942275929 457
0.7595726149133598 458
0.6490814370993955 459
0.7403468258977124 460
0.5454890923595141 461
0.5884963228622546 462
0.7651433471551012 463
0.5154396114306938 464
0.6325895410243423 465
0.6857992205317531 466
0.593331098071646 467
0.6743050784851994 468
0.6455489990035197 469
0.5003663678317228 470
0.5601928875680922 471
0.3766563077456393 472
0.7005478308842471 473
0.71357062848896 474
0.7710966656995506 475
0.6124266341907658 476
0.6357250455879513 477
0.7602158043342471 478
0.5374675389595509 479
0.5656524016514577 480
0.6083180880215178 481
0.613283974457063 482
0.5492968470317733 483
0.5554855789531343 484
0.5399580568368285 485
0.6290949629341738 486
0.5937747444106358 487
0.7478395990541278 488
0.6452448563442009 489
0.5264597758878543 490
0.7795071299480508 491
0.6052546035928515 492
0.6292710254920182 493
0.6699392446759362 494
0.5523273980590145 495
0.7028327594867316 496
0.6415260814773667 497
0.6711452962767753 498
0.7764484272513023 499
0.6924828241932157 500
0.5980375793643775 501
0.5754440391176254 502
0.6434582844996894 503
0.5343226760729685 504
0.6429656778239417 505
0.6851787505009574 506
0.769375128175642 507
0.6992970061934547 508
0.6557602123507034 509
0.6033643429687866 510
0.6207484841996596 511
0.6471966503519457 512
0.7253061811825785 513
0.667807472928321 514
0.78921510973492 515
0.7078236614764273 516
0.7603830975271995 517
0.5954624900347074 518
0.6655713169345022 519
0.7073727018086253 520
0.6473710995499312 521
0.5162861326385669 522
0.583541229472275 523
0.5405346174021293 524
0.5317023029118053 525
0.6275043206785273 526
0.6906582058732762 527
0.7670482074559342 528
0.6518332642653928 529
0.6588683324882543 530
0.5721352513241045 531
0.6254559296631346 532
0.7379172759230819 533
0.5224711540289169 534
0.5882987016829531 535
0.631094217569115 536
0.546173469783612 537
0.6795618154886887 538
0.5815842262403241 539
0.7003427048495781 540
0.5946704492904595 541
0.6753259593576275 542
0.5956478585702442 543
0.7106206373179953 544
0.4693297805470914 545
0.7275611531539452 546
0.3422708320350021 547
0.7060220078541206 548
0.5218671851481156 549
0.62992162346378 550
0.6585523093362093 551
0.515204986257282 552
0.7328457260613643 553
0.6240948635582859 554
0.707351365849627 555
0.5740751417779242 556
0.5262596465658976 557
0.696577062562732 558
0.7034768420899947 559
0.6107194796077637 560
0.491742432271851 561
0.7091237667721104 562
0.5955145917062187 563
0.6615135326363659 564
0.6910939874030952 565
0.7993878843287959 566
0.6668574189316663 567
0.7136033328954852 568
0.5951397726525282 569
0.647582421255383 570
0.6622393314174229 571
0.6827373484712309 572
0.6303641708432792 573
0.5842865655525793 574
0.6736074004811778 575
0.657639002765869 576
0.7582369133547905 577
0.6734209327275962 578
0.6114275004485188 579
0.5991422525085062 580
0.6507416623339471 581
0.5062262972999134 582
0.62791962535668 583
0.5281288401491697 584
0.584325144621058 585
0.7054620189446918 586
0.6213377088094425 587
0.7004269325942735 588
0.6993451261076742 589
0.5978425343482408 590
0.6946847597857815 591
0.697626171562004 592
0.7055849567858616 593
0.6043769589459229 594
0.4021921454468036 595
0.5736320315755554 596
0.5733575501300967 597
0.5748583936151617 598
0.5218593188163587 599
0.5245532394358633 600
0.5855117894562749 601
0.7184844828597551 602
0.5904042702220177 603
0.5518793915225546 604
0.7590447927536008 605
0.49903135528923737 606
0.6114234565373313 607
0.6838044443169249 608
0.6348725366530799 609
0.4877448759780192 610
0.6216583057060687 611
0.6126534725060269 612
0.6090117546669426 613
0.6706938489592211 614
0.5983398033117777 615
0.38708533310408144 616
0.5846895796085769 617
0.6900290868109431 618
0.6176500309674271 619
0.5202771244243971 620
0.7248068050501552 621
0.6046302606728038 622
0.5294563783763041 623
0.7346751915061485 624
0.6003385368485442 625
0.6829659775327745 626
0.5189376381529412 627
0.6662338034389915 628
0.6550621144305264 629
0.6186165375191761 630
0.6901357083483923 631
0.700649864493755 632
0.6568435380785942 633
0.5321854927749733 634
0.597752508764029 635
0.6894966610592987 636
0.6772366579653022 637
0.7670084077732819 638
0.558579575040395 639
0.5747843149287601 640
0.684923406015791 641
0.6787705002317546 642
0.6079120464104527 643
0.4929123702981564 644
0.6926196620157856 645
0.6039381876127867 646
0.4666989685129679 647
0.6113612971253628 648
0.6550993833290273 649
0.7001589285181922 650
0.6145937605577445 651
0.7505461786388131 652
0.7235272766387845 653
0.6612459269446502 654
0.659647234557584 655
0.5974857741757207 656
0.4729279614739843 657
0.6782755093921684 658
0.6745699941813219 659
0.7280109902726443 660
0.7644859325292941 661
0.5429014429388411 662
0.5221214662765095 663
0.4969552335711298 664
0.6718117885618918 665
0.5998369865433231 666
0.7094943923406172 667
0.7262529514810914 668
0.7436745605911853 669
0.7467166347492697 670
0.5289693380886127 671
0.6739738288733905 672
0.7399391686461827 673
0.7085434391937311 674
0.6382304191936218 675
0.6586967564860611 676
0.5555038987590057 677
0.71490876826033 678
0.6736173079524017 679
0.6200758895464311 680
0.5216906456149132 681
0.7345369196876372 682
0.7038706886032303 683
0.6049305509133244 684
0.6229071754990179 685
0.8307396531542872 686
0.6456405955145752 687
0.5723444402985198 688
0.7923156967272911 689
0.6192818631117009 690
0.6641391038908867 691
0.6621665280805937 692
0.6508317152452718 693
0.7075675327294004 694
0.7162243822347638 695
0.6544247005716566 696
0.553765149498723 697
0.7606207291275964 698
0.6481926647228666 699
0.49269052174655126 700
0.6920797635431739 701
0.5520554415727366 702
0.7247699075372789 703
0.5561581796515569 704
0.6829479126944009 705
0.7292285260977531 706
0.668788597969219 707
0.6286781358098628 708
0.5405839354660631 709
0.6533316194345233 710
0.7111802876654476 711
0.8159928451470271 712
0.7475500939438192 713
0.6591159249558454 714
0.683385355474224 715
0.7217976052870927 716
0.7286596442613336 717
0.3593692617821508 718
0.6528747237989931 719
0.5556695135084571 720
0.5966034512614866 721
0.6804447810930374 722
0.6894463629600805 723
0.6471008019430176 724
0.608182581136064 725
0.6593955361972461 726
0.6912829533541899 727
0.6052263674588891 728
0.6176878862835339 729
0.7597269040373931 730
0.5337030269570905 731
0.7824042774022395 732
0.6786101660656896 733
0.605719583902792 734
0.5765813761128911 735
0.6212779311958336 736
0.5159469292643702 737
0.6857476844152497 738
0.6088533821710079 739
0.6273827239475848 740
0.5889053835653886 741
0.74274762765894 742
0.7510500276539752 743
0.6027772473829198 744
0.6123543049765177 745
0.6656802033980536 746
0.5682767143962439 747
0.6025404963382144 748
0.5260500679070397 749
0.5676037109676628 750
0.7145878111810364 751
0.7573509091406929 752
0.68549216294519 753
0.720156752120834 754
0.6136643723030089 755
0.6141244770802745 756
0.7423399110221711 757
0.6108583943004906 758
0.6454660335507125 759
0.6559980995387682 760
0.6762881596476198 761
0.717427328595974 762
0.6494942770578132 763
0.633957901889569 764
0.6747135088486093 765
0.6338987567375163 766
0.6267393499491442 767
0.5457208770335354 768
0.7572823845070212 769
0.6349718817165002 770
0.695503209439134 771
0.674806034294505 772
0.6156618678442738 773
0.5725194932528859 774
0.5877855920593356 775
0.5683783955962897 776
0.37386234046297717 777
0.7043691720797424 778
0.6684198436779563 779
0.6648219640002035 780
0.804407640304367 781
0.7138666535365197 782
0.763964627362082 783
0.6473009711936534 784
0.6483774990568415 785
0.6459297937893319 786
0.6587111569517832 787
0.6941316183485737 788
0.4369445210218952 789
0.7133823055228757 790
0.6983292516477299 791
0.7757238629386152 792
0.7468112982817021 793
0.668809821154762 794
0.5732734346489912 795
0.7186095888973218 796
0.6166066892651231 797
0.6431502984615115 798
0.7431202146589884 799
0.6442224657233399 800
0.5428088930713735 801
0.6226287657374523 802
0.6653252272094138 803
0.5609223702807227 804
0.6136276555756676 805
0.6547955070147489 806
0.7498720249794688 807
0.40121009503663596 808
0.5812680901095926 809
0.5541527304920095 810
0.6371186757954788 811
0.6704144187283165 812
0.540773380923877 813
0.7910042007895016 814
0.6229781800369643 815
0.618156851990938 816
0.711908416131634 817
0.6589466319629027 818
0.6642645264569772 819
0.5697878121036803 820
0.7882982218714687 821
0.6520954534956291 822
0.6004379926939446 823
0.46190249662746774 824
0.7268632231327684 825
0.6680061351248499 826
0.7630109642474578 827
0.6532128206534782 828
0.6411589323930716 829
0.4961048230436069 830
0.708765861733945 831
0.7768840789736845 832
0.593254157127826 833
0.7008477726385278 834
0.6492826645048335 835
0.567624025048528 836
0.6406608563402335 837
0.6240350371473333 838
0.5876235567498154 839
0.7367786704919503 840
0.7599737635094591 841
0.7300966953428936 842
0.7137669776580966 843
0.662057521844188 844
0.5065397323996659 845
0.6235118453904134 846
0.6213008920584138 847
0.5978377258606912 848
0.7000335035197481 849
0.7206999632498701 850
0.6071774163862249 851
0.6381668431961194 852
0.6297898496379472 853
0.5691142036181881 854
0.6267435840853159 855
0.5543006468123176 856
0.5174390467123702 857
0.7549911010286214 858
0.5390756179218961 859
0.7756192646448714 860
0.5670836065023321 861
0.656512183001787 862
0.6053963527614759 863
0.6803129840805371 864
0.5651889754679178 865
0.6179958560855743 866
0.6064671975953853 867
0.5691754853090145 868
0.6367687212906628 869
0.5881858619558593 870
0.5351972608020876 871
0.6729682148003441 872
0.6288837501109257 873
0.6904297021887773 874
0.6647117250519108 875
0.6487790572414714 876

In [90]:
np.argmax(scores)

433

In [91]:
scores[np.argmax(scores)]

0.8455753664645759

In [94]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_pred = pipe.predict(x_test)
r2_score(y_test,y_pred)

0.8455753664645759

In [96]:
import pickle

In [97]:
pickle.dump(pipe,open('LinearRegressionModel.pk1','wb'))

In [102]:
car

,Unnamed: 0,name,company,year,Price,kms_driven,fuel_type
0,0,Hyundai Santro Xing,Hyundai,2007,80000,45000,Petrol
1,1,Mahindra Jeep CL550,Mahindra,2006,425000,40,Diesel
2,2,Hyundai Grand i10,Hyundai,2014,325000,28000,Petrol
3,3,Ford EcoSport Titanium,Ford,2014,575000,36000,Diesel
4,4,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...,...
810,811,Maruti Suzuki Ritz,Maruti,2011,270000,50000,Petrol
811,812,Tata Indica V2,Tata,2009,110000,30000,Diesel
812,813,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
813,814,Tata Zest XM,Tata,2018,260000,27000,Diesel
814,815,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [106]:
pipe.predict(pd.DataFrame([['2','Hyundai Grand i10','Hyundai','2014','28000','Petrol']]),
             columns=['Unnamed: 0','name','company','year','kms_driven','fuel_type'])

ValueError: columns are missing: {'kms_driven', 'Unnamed: 0', 'year'}